### ISSUE TITLE
Sites with certain redirects fail in chromedevtools module

### ISSUE THREAD

**Issue by sxxs** [PrivacyScore/privacyscanner#17]
Reproduce with `privacyscanner scan http://www.bamberg.de/`, a site, which redirects the user via to http://www.stadt.bamberg.de/ as follows:

`<meta http-equiv="refresh" content="1; URL=http://www.stadt.bamberg.de/">`

The following output is generated in this case.

`/usr/local/lib/python3.7/site-packages/pychrome/tab.py:174: UserWarning: Page.getResourceContent error: No resource with given URL found
  warnings.warn("%s error: %s" % (_method, result['error']['message']))
websocket exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pychrome/tab.py", line 121, in _recv_loop
    message_json = self._ws.recv()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 310, in recv
    opcode, data = self.recv_data()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 327, in recv_data
    opcode, frame = self.recv_data_frame(control_frame)
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 340, in recv_data_frame
    frame = self.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 374, in recv_frame
    return self.frame_buffer.recv_frame()
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 361, in recv_frame
    self.recv_header()
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 309, in recv_header
    header = self.recv_strict(2)
  File "/usr/local/lib/python3.7/site-packages/websocket/_abnf.py", line 396, in recv_strict
    bytes_ = self.recv(min(16384, shortage))
  File "/usr/local/lib/python3.7/site-packages/websocket/_core.py", line 449, in _recv
    return recv(self.sock, bufsize)
  File "/usr/local/lib/python3.7/site-packages/websocket/_socket.py", line 94, in recv
    "Connection is already closed.")
websocket._exceptions.WebSocketConnectionClosedException: Connection is already closed.
chromedevtools> 2019-02-27 16:13:22,462: [ERROR] Scan module `chromedevtools` failed. (scanner.py:197)`

**Comment by hprid** [comment]
This is related the the way the detection of the final URL currently works. We follow the redirect chain from the HTTP headers and take the last response in that row. However, if a site uses a JavaScript or meta redirect, we do not see that redirect and try to access the resource for the URL after all header redirects. This resource is already vanished by Chrome because the current frame loaded the site after the JS/meta redirect.
I will look into different ways to find the final URL. This must work with JavaScript and meta redirect, and manipulated navigation history (e.g., in single page apps).
