### ISSUE TITLE
Python 3.5.X support?

### ISSUE THREAD

**Issue by malexmave** [PrivacyScore/privacyscanner#5]
Do you want to support Python 3.5.X? At the moment, the code crashes when run with that Python version [due to a PosixPath problem](https://stackoverflow.com/questions/42694112/when-using-pathlib-getting-error-typeerror-invalid-file-posixpathexample-t). So, when I run `privacyscanner scan http://google.com`, I get:

```python
Traceback (most recent call last):
  File "/home/max/tmp/privacyscanner/privacyscanner/venv/bin/privacyscanner", line 11, in <module>
    load_entry_point('privacyscanner', 'console_scripts', 'privacyscanner')()
  File "/home/max/tmp/privacyscanner/privacyscanner/privacyscanner/scanner.py", line 200, in main
    args.func(args)
  File "/home/max/tmp/privacyscanner/privacyscanner/privacyscanner/scanner.py", line 97, in scan_site
    with open(result_file, 'w') as f:
TypeError: invalid file: PosixPath('google.com_548da37adc/results.json')
```

If this is working as intended because you do not want to support Python 3.5, feel free to close as wontfix and I will try to get a more modern Python setup on my Laptop.

**Comment by malexmave** [comment]
Looks like 9fdf131c60fd417df3fef58da136fc3ac8733878 successfully fixed this, thanks!
